### ISSUE TITLE
How to access cluster membership?

### ISSUE THREAD

**Issue by MathieuBo** [SpeakEasy-2/python-speakeasy2#1]
Hi!

I wanted to use SpeakEasy2 to reproduce the results from a paper but it is unclear to me how I can access the final cluster membership after the clustering is done. 
Any help will be much appreciated!

**Comment by DavidRConnell** [comment]
Hi, I assume this is closed because you figured it out but the results are stored in an igraph VertexCluster object. Admittedly this obscures seeing the actual results a bit but it's useful when working with the igraph package and has some nice features like being able to calculate modularity with `memb.modularity` or `memb.q`.

To view the raw membership, you can use `print` to show a list of nodes for each community or to convert it to a normal python list, get the object's `membership` field (i.e. `memb.membership`). I've added this information to the README.

Coincidentally, I just ran some benchmarks to reproduce the publication results myself since this is a rewrite of the implementation used there and I want to confirm it behaves the same. The results can be found [here](https://github.com/SpeakEasy-2/libspeakeasy2/tree/master/benchmarks).

In performing those benchmarks I did find an issue with calculating skew that affects how well the algorithm runs on graphs with a highly skewed weight distribution. This has been fixed so please update to the newer version on PyPI.

I also intend on uploading the synthetic LFR benchmark graphs we used in the original publication somewhere so they can be used. And will likely put together a script at some point to perform similar comparisons as we had in the publication. The igraph package includes the Leiden, Louvain, and infomap so it should be easy.

**Comment by MathieuBo** [comment]
Indeed but thanks for your answer and the benchmark results!
